config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  resources :products do
    get 'all'
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  scope :three_most_recent, -> { order(created_at: :desc).limit(3) }

  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
      .joins(:reviews)
      .group("products.id")
      .order("reviews_count DESC")
      .limit(1)
    )}

  scope :local, -> { where('origin LIKE ?', '%, USA' )}  

  validates(:name, :cost, :origin, :notes, :presence => true)

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates(:author, :rating, :presence => true)
  validates(:content_body, {length: { in: 50..250 }, :presence => true})
  validates_numericality_of(:rating, { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 })

  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.three_most_recent
    @reviews = Product.most_reviews
    @localProducts = Product.local
  end

  def show
    @product = Product.find(params[:id])
  end

  def all
    @products = Product.all
    render :all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Coffee successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Coffee successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Coffee successfully deleted!"
      redirect_to products_path
    else
      render :show
    end
  end

private
  def product_params
    params.require(:product).permit(:name, :cost, :origin, :notes)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/products/_form.html.erb
<%= render "errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.label :notes %>
  <%= f.text_field :notes %>
  <%= f.submit %>
<% end %>

app/views/products/all.html.erb
<h4 class="home"><%= link_to "home", products_path %></h4>
<hr>
<h3>All Coffees</h3>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %><br></li>
  <% end %>
</ul>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h4 class="admin"><%= link_to 'admin', new_product_path %></h4>

<div class="jumbotron">
  <h1>Speciality Coffee Co.</h1>
  <p>Speciality Coffee Company exists to satisfy all your covfefe and caffeination needs.</p>
  <p>Explore our site to learn about our products or add a review!</p>
</div>

<div class="row">
  <div class="col-sm-4" class="sub-header">
    <h3>New Coffees</h3>
    <ul>
      <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %><br></li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4" class="sub-header">
    <h3>Local Coffee</h3>
    <ul>
      <% @localProducts.each do |product| %>
      <li><%= link_to product.name, product_path(product)%><br></li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4" class="sub-header">
    <h3>Most Reviewed Coffee</h3>
    <ul>
      <% @reviews.each do |review| %>
      <li><%= link_to review.name, product_path(review)%><br></li>
      <% end %>
    </ul>
  </div>
</div>

<hr>
<h3><%= link_to "all coffees", product_all_path(:product_id) %></h3>

app/views/products/new.html.erb
<h1>Add a Coffee</h1>

<%=  render 'form' %>
<br>
<%= link_to "home", products_path %>

app/views/products/show.html.erb
<h1 class="product-name"><%= @product.name %></h1>
<hr>
<div class="row">
  <div class="col-sm-6">
    <h3>Origin: <%= @product.origin %></h3>
    <p>Tasting Notes: <%= @product.notes %></p>
    <p><em>$<%= @product.cost %></em></p>


    <%= link_to "edit coffee", edit_product_path %><br>
    <p><%= link_to "delete coffee", product_path(@product),
    :data => {:confirm => "Remove coffee from product list?",
      :method => "delete"} %></p>
  </div>
  <div class="col-sm-6">

  </div>

</div>

<% if @product.reviews.any? %>
  <h4>Reviews</h4>
  <ul>
    <% @product.reviews.each do |review| %>
      <li class="review-list">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h5><%= review.author %> -
           rating: <%= review.rating %>/5</h5>
          </div>
          <div class="panel-body">
            <%= review.content_body %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <h4><%= link_to 'new review', new_product_review_path(@product) %></h4>

<% else %>
  <p>Be the first to review this coffee!</p>
  <%= link_to 'add review', new_product_review_path(@product) %>
<% end %>
<div class="links">
  <h5><%= link_to "all coffees", product_all_path(:id) %></h5>
  <h5><%= link_to "home", products_path %></h5>  
</div>

app/views/reviews/_form.html.erb
<%= render "products/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Review <%= @product.name %></h1>

<%= render 'form' %>